# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/ssd.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protos import anchor_generator_pb2 as protos_dot_anchor__generator__pb2
from protos import box_coder_pb2 as protos_dot_box__coder__pb2
from protos import box_predictor_pb2 as protos_dot_box__predictor__pb2
from protos import hyperparams_pb2 as protos_dot_hyperparams__pb2
from protos import image_resizer_pb2 as protos_dot_image__resizer__pb2
from protos import matcher_pb2 as protos_dot_matcher__pb2
from protos import losses_pb2 as protos_dot_losses__pb2
from protos import post_processing_pb2 as protos_dot_post__processing__pb2
from protos import region_similarity_calculator_pb2 as protos_dot_region__similarity__calculator__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/ssd.proto',
  package='protos',
  syntax='proto2',
  serialized_pb=_b('\n\x10protos/ssd.proto\x12\x06protos\x1a\x1dprotos/anchor_generator.proto\x1a\x16protos/box_coder.proto\x1a\x1aprotos/box_predictor.proto\x1a\x18protos/hyperparams.proto\x1a\x1aprotos/image_resizer.proto\x1a\x14protos/matcher.proto\x1a\x13protos/losses.proto\x1a\x1cprotos/post_processing.proto\x1a)protos/region_similarity_calculator.proto\"\xe3\x03\n\x03Ssd\x12\x13\n\x0bnum_classes\x18\x01 \x01(\x05\x12+\n\rimage_resizer\x18\x02 \x01(\x0b\x32\x14.protos.ImageResizer\x12\x36\n\x11\x66\x65\x61ture_extractor\x18\x03 \x01(\x0b\x32\x1b.protos.SsdFeatureExtractor\x12#\n\tbox_coder\x18\x04 \x01(\x0b\x32\x10.protos.BoxCoder\x12 \n\x07matcher\x18\x05 \x01(\x0b\x32\x0f.protos.Matcher\x12\x41\n\x15similarity_calculator\x18\x06 \x01(\x0b\x32\".protos.RegionSimilarityCalculator\x12+\n\rbox_predictor\x18\x07 \x01(\x0b\x32\x14.protos.BoxPredictor\x12\x31\n\x10\x61nchor_generator\x18\x08 \x01(\x0b\x32\x17.protos.AnchorGenerator\x12/\n\x0fpost_processing\x18\t \x01(\x0b\x32\x16.protos.PostProcessing\x12+\n\x1dnormalize_loss_by_num_matches\x18\n \x01(\x08:\x04true\x12\x1a\n\x04loss\x18\x0b \x01(\x0b\x32\x0c.protos.Loss\"\x86\x01\n\x13SsdFeatureExtractor\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x1b\n\x10\x64\x65pth_multiplier\x18\x02 \x01(\x02:\x01\x31\x12\x15\n\tmin_depth\x18\x03 \x01(\x05:\x02\x31\x36\x12-\n\x10\x63onv_hyperparams\x18\x04 \x01(\x0b\x32\x13.protos.Hyperparams')
  ,
  dependencies=[protos_dot_anchor__generator__pb2.DESCRIPTOR,protos_dot_box__coder__pb2.DESCRIPTOR,protos_dot_box__predictor__pb2.DESCRIPTOR,protos_dot_hyperparams__pb2.DESCRIPTOR,protos_dot_image__resizer__pb2.DESCRIPTOR,protos_dot_matcher__pb2.DESCRIPTOR,protos_dot_losses__pb2.DESCRIPTOR,protos_dot_post__processing__pb2.DESCRIPTOR,protos_dot_region__similarity__calculator__pb2.DESCRIPTOR,])




_SSD = _descriptor.Descriptor(
  name='Ssd',
  full_name='protos.Ssd',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='num_classes', full_name='protos.Ssd.num_classes', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='image_resizer', full_name='protos.Ssd.image_resizer', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='feature_extractor', full_name='protos.Ssd.feature_extractor', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='box_coder', full_name='protos.Ssd.box_coder', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='matcher', full_name='protos.Ssd.matcher', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='similarity_calculator', full_name='protos.Ssd.similarity_calculator', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='box_predictor', full_name='protos.Ssd.box_predictor', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='anchor_generator', full_name='protos.Ssd.anchor_generator', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='post_processing', full_name='protos.Ssd.post_processing', index=8,
      number=9, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='normalize_loss_by_num_matches', full_name='protos.Ssd.normalize_loss_by_num_matches', index=9,
      number=10, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=True,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='loss', full_name='protos.Ssd.loss', index=10,
      number=11, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=282,
  serialized_end=765,
)


_SSDFEATUREEXTRACTOR = _descriptor.Descriptor(
  name='SsdFeatureExtractor',
  full_name='protos.SsdFeatureExtractor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='protos.SsdFeatureExtractor.type', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='depth_multiplier', full_name='protos.SsdFeatureExtractor.depth_multiplier', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(1),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='min_depth', full_name='protos.SsdFeatureExtractor.min_depth', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=16,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='conv_hyperparams', full_name='protos.SsdFeatureExtractor.conv_hyperparams', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=768,
  serialized_end=902,
)

_SSD.fields_by_name['image_resizer'].message_type = protos_dot_image__resizer__pb2._IMAGERESIZER
_SSD.fields_by_name['feature_extractor'].message_type = _SSDFEATUREEXTRACTOR
_SSD.fields_by_name['box_coder'].message_type = protos_dot_box__coder__pb2._BOXCODER
_SSD.fields_by_name['matcher'].message_type = protos_dot_matcher__pb2._MATCHER
_SSD.fields_by_name['similarity_calculator'].message_type = protos_dot_region__similarity__calculator__pb2._REGIONSIMILARITYCALCULATOR
_SSD.fields_by_name['box_predictor'].message_type = protos_dot_box__predictor__pb2._BOXPREDICTOR
_SSD.fields_by_name['anchor_generator'].message_type = protos_dot_anchor__generator__pb2._ANCHORGENERATOR
_SSD.fields_by_name['post_processing'].message_type = protos_dot_post__processing__pb2._POSTPROCESSING
_SSD.fields_by_name['loss'].message_type = protos_dot_losses__pb2._LOSS
_SSDFEATUREEXTRACTOR.fields_by_name['conv_hyperparams'].message_type = protos_dot_hyperparams__pb2._HYPERPARAMS
DESCRIPTOR.message_types_by_name['Ssd'] = _SSD
DESCRIPTOR.message_types_by_name['SsdFeatureExtractor'] = _SSDFEATUREEXTRACTOR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Ssd = _reflection.GeneratedProtocolMessageType('Ssd', (_message.Message,), dict(
  DESCRIPTOR = _SSD,
  __module__ = 'protos.ssd_pb2'
  # @@protoc_insertion_point(class_scope:protos.Ssd)
  ))
_sym_db.RegisterMessage(Ssd)

SsdFeatureExtractor = _reflection.GeneratedProtocolMessageType('SsdFeatureExtractor', (_message.Message,), dict(
  DESCRIPTOR = _SSDFEATUREEXTRACTOR,
  __module__ = 'protos.ssd_pb2'
  # @@protoc_insertion_point(class_scope:protos.SsdFeatureExtractor)
  ))
_sym_db.RegisterMessage(SsdFeatureExtractor)


# @@protoc_insertion_point(module_scope)
